apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegraf
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: telegraf-secret
    creationPolicy: Owner
    template:
      data:
        TELEGRAF_INFLUX_TOKEN: "{{ .INFLUX_TOKEN }}"      
  dataFrom:
    - find:
        path: TELEGRAF_
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"