apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      data:
        ADMIN_USER: "{{ .GRAFANA_ADMIN_USER }}"
        ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"      
  dataFrom:
    - find:
        path: GRAFANA_
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"