---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mqtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1883
            runAsGroup: 1883
            fsGroup: 1883
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 1.6.15-openssl@sha256:9dbbd8eb3eb0be55648e4c7a6e6f91d9ba75cf0d83325bd42349804aaa7c25a4
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M
    service:
      mqtt:
        controller: mqtt
        type: LoadBalancer
        ports:
          mqtt:
            port: 1883
      mqtt-http:
        controller: mqtt
        ports:
          http:
            port: 8080
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          mqtt:
            app:
              - path: /mosquitto/data/
    route:
      app:
        hostnames:
          - mqtt.apps.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: mqtt-http
                port: 8080