---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: influxdata

    